version: '3.8'

services:
  web:
    build: .
    container_name: amazon_backend_web
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=Amazon Backend System
      - APP_ENV=production
      - DEBUG=False
      - API_V1_STR=/api/v1
      - SECRET_KEY=supersecretjwtkeyforamazonbackendenterprise2026productionuseonly!
      - DATABASE_URL=postgresql+asyncpg://amazon_user:amazon_password@postgres:5432/amazon_db
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_DB_NAME=amazon_mongo_db
      - REDIS_URL=redis://redis:6379/0
      - CHROMADB_DIR=/app/uploads/chromadb_store
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres
      - mongo
      - redis

  postgres:
    image: postgres:16-alpine
    container_name: amazon_postgres
    environment:
      POSTGRES_USER: amazon_user
      POSTGRES_PASSWORD: amazon_password
      POSTGRES_DB: amazon_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7-jammy
    container_name: amazon_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: amazon_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data:
